# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 15:31
from __future__ import unicode_literals

from django.db import migrations
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='finished_at',
            field=model_utils.fields.MonitorField(blank=True, default=None, monitor='active', null=True, verbose_name='finished at', when=set([False])),
        ),
    ]
