# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 17:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_ticket_finished_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['-created', 'active']},
        ),
        migrations.AlterField(
            model_name='task',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task', to='tickets.Ticket', verbose_name='task'),
        ),
    ]
