# Generated by Django 2.0.3 on 2018-03-23 22:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_auto_20171125_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='files', to='tickets.Ticket', verbose_name='ticket'),
        ),
        migrations.AlterField(
            model_name='log',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='logs', to='tickets.Task', verbose_name='task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='creator', to=settings.AUTH_USER_MODEL, verbose_name='creator'),
        ),
        migrations.AlterField(
            model_name='task',
            name='executor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='executor', to=settings.AUTH_USER_MODEL, verbose_name='executor'),
        ),
        migrations.AlterField(
            model_name='task',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task', to='tickets.Ticket', verbose_name='task'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ticket', to=settings.AUTH_USER_MODEL, verbose_name='requester'),
        ),
    ]
