# Generated by Django 2.0.5 on 2018-05-23 02:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_auto_20180522_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to=settings.AUTH_USER_MODEL, verbose_name='requester'),
        ),
    ]
