# Generated by Django 2.0.5 on 2018-05-23 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_auto_20180522_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='tickets.Ticket', verbose_name='task'),
        ),
    ]
