# Generated by Django 2.0.5 on 2018-05-23 02:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_auto_20180522_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opened', to=settings.AUTH_USER_MODEL, verbose_name='creator'),
        ),
    ]
